# Generated by Django 4.2.11 on 2025-07-23 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Archivo de audio')),
                ('duration', models.FloatField(default=0.0, verbose_name='Duración (segundos)')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño de archivo (bytes)')),
                ('file_format', models.CharField(blank=True, max_length=10, verbose_name='Formato')),
                ('sample_rate', models.PositiveIntegerField(default=0, verbose_name='Tasa de muestreo (Hz)')),
                ('channels', models.PositiveSmallIntegerField(default=0, verbose_name='Canales')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Archivo de audio',
                'verbose_name_plural': 'Archivos de audio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('text', models.TextField(blank=True, verbose_name='Texto transcrito')),
                ('language', models.CharField(choices=[('es-ES', 'Español'), ('en-US', 'Inglés'), ('fr-FR', 'Francés'), ('de-DE', 'Alemán'), ('it-IT', 'Italiano')], default='es-ES', max_length=5, verbose_name='Idioma')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=10, verbose_name='Estado')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Conteo de palabras')),
                ('duration', models.FloatField(default=0.0, verbose_name='Duración procesada (segundos)')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('vad_enabled', models.BooleanField(default=True, verbose_name='Detección de actividad de voz (VAD)')),
                ('noise_reduction', models.BooleanField(default=True, verbose_name='Reducción de ruido')),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='core.audiofile', verbose_name='Archivo de audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transcripción',
                'verbose_name_plural': 'Transcripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Foto de perfil')),
                ('api_usage_count', models.PositiveIntegerField(default=0, verbose_name='Conteo de uso de API')),
                ('total_audio_duration', models.FloatField(default=0.0, verbose_name='Duración total de audio (segundos)')),
                ('total_words_transcribed', models.PositiveIntegerField(default=0, verbose_name='Total de palabras transcritas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('text', models.TextField(blank=True, verbose_name='Texto traducido')),
                ('source_language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano')], max_length=5, verbose_name='Idioma origen')),
                ('target_language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano')], max_length=5, verbose_name='Idioma destino')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.transcription', verbose_name='Transcripción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
